apiVersion: integration/v1
kind: Trigger
name: template
version: 1
summary: Step template
description: |
  This is a template for a simple step.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker
